# Generated by Django 3.1 on 2020-08-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeliveryMan',
            fields=[
                ('delivery_man_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('delivery_man_code', models.CharField(max_length=5, verbose_name='代码')),
                ('delivery_man_name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '送餐员',
                'db_table': 'data_delivery_man',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataDeliveryPlatform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('platform_code', models.CharField(max_length=5, verbose_name='代码')),
                ('platform', models.CharField(max_length=20, verbose_name='平台名')),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='平台抽成')),
            ],
            options={
                'verbose_name': '送餐平台',
                'db_table': 'data_delivery_platform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataDish',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dcategory', models.CharField(max_length=20)),
                ('dcode', models.CharField(max_length=10, unique=True)),
                ('dname', models.CharField(max_length=255)),
                ('dprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dtax', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dingredients', models.CharField(blank=True, max_length=512, null=True)),
                ('dondelete', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '菜品清单',
                'db_table': 'data_dish',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataDishCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('subcategory_id', models.IntegerField(unique=True)),
                ('category', models.CharField(max_length=10, verbose_name='类别名')),
                ('subcategory', models.CharField(max_length=10, verbose_name='子类别名')),
            ],
            options={
                'verbose_name': '菜品类别',
                'db_table': 'data_dish_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataNoteBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('note_category_id', models.IntegerField(verbose_name='备注类别编号')),
                ('note_category', models.CharField(max_length=20, verbose_name='备注类别')),
                ('note_content', models.CharField(max_length=250, verbose_name='备注内容')),
            ],
            options={
                'verbose_name': '备注库',
                'db_table': 'data_note_base',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataSpecialNote',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=250, verbose_name='备注内容')),
                ('component', models.CharField(max_length=250, verbose_name='编号明细')),
            ],
            options={
                'verbose_name': '备注',
                'db_table': 'data_special_note',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataTicket',
            fields=[
                ('ticket_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ticket_time', models.CharField(max_length=20, verbose_name='订单时间')),
                ('type', models.IntegerField(choices=[(0, '堂食'), (1, '打包'), (2, '外送')], default=0, verbose_name='订单类型')),
                ('table_num', models.CharField(max_length=20, verbose_name='订单号/桌号')),
                ('person_quantity', models.IntegerField(default=1)),
                ('client_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户姓名')),
                ('client_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='客户地址')),
                ('client_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='客户电话')),
                ('ticket_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='订单备注')),
                ('ticket_status', models.IntegerField(choices=[(0, '预约订单'), (1, '准备中'), (2, '已完成'), (3, '已取消')], default=1, verbose_name='订单状态')),
                ('payment_status', models.IntegerField(choices=[(0, '未付款'), (1, '付款中'), (2, '已付款')], default=0, verbose_name='支付状态')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='整单价格')),
                ('ticket_discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='整单折扣')),
                ('pay_by_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金支付')),
                ('pay_by_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='饭票支付')),
                ('pay_by_card', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='银行卡支付')),
                ('pay_by_check', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='支票支付')),
                ('pay_by_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='转账支付')),
                ('pay_by_wechat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='微信支付')),
                ('pay_by_alipay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='支付宝支付')),
                ('pay_by_another', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他支付')),
                ('zrapport_condition', models.IntegerField(choices=[(0, '未日结算'), (1, '完成日结算')], default=0, verbose_name='日结状态')),
                ('ticket_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='整单价格')),
                ('ticket_emergency', models.IntegerField(choices=[(0, '普通'), (1, '优先'), (2, '最紧急')], default=0, verbose_name='加急状态')),
                ('finish_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='完成时间')),
                ('delivery_man', models.ForeignKey(db_column='f_delivery_man', default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_beta_02.datadeliveryman', verbose_name='送餐员')),
                ('delivery_platform', models.ForeignKey(db_column='f_delivery_platform', default=12, on_delete=django.db.models.deletion.CASCADE, to='restaurant_beta_02.datadeliveryplatform', verbose_name='送餐平台')),
            ],
            options={
                'verbose_name': '订单表',
                'db_table': 'data_ticket',
            },
        ),
        migrations.CreateModel(
            name='DataOrder',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='order编号')),
                ('order_time', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('order_note', models.CharField(default=1, max_length=50, verbose_name='菜品备注')),
                ('prepare_status', models.IntegerField(choices=[(0, '预定'), (1, '准备中'), (2, '已备齐'), (3, '已完成')], default=1, verbose_name='准备状态')),
                ('discount_type', models.IntegerField(choices=[(0, '参与整单打折'), (1, '不参与整单打折')], default=0, verbose_name='打折类型')),
                ('extra_discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='特殊折扣')),
                ('emergency', models.IntegerField(choices=[(0, '普通'), (1, '优先'), (2, '最紧急')], default=0, verbose_name='加急状态')),
                ('person', models.IntegerField(default=1, verbose_name='客户')),
                ('finish_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='完成时间')),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='restaurant_beta_02.datadish', to_field='dcode')),
                ('tid', models.ForeignKey(db_column='tid', on_delete=django.db.models.deletion.CASCADE, to='restaurant_beta_02.dataticket', verbose_name='订单id')),
            ],
            options={
                'verbose_name': '订单流水',
                'db_table': 'data_order',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='datadish',
            name='dsubcategory',
            field=models.ForeignKey(db_column='dsubcategory', on_delete=django.db.models.deletion.CASCADE, to='restaurant_beta_02.datadishcategory', to_field='subcategory_id', verbose_name='类别'),
        ),
    ]
