# Generated by Django 3.1 on 2020-08-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0004_auto_20200811_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanotebase',
            name='max',
            field=models.IntegerField(default=0, verbose_name='最大位数'),
        ),
    ]
