# Generated by Django 3.1 on 2020-11-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0006_notetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorder',
            name='o_note',
            field=models.CharField(db_column='o_note', max_length=250, verbose_name='菜品备注'),
        ),
    ]
