# Generated by Django 3.1 on 2021-04-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0007_auto_20201101_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='ticket_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tva总'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='ticket_tax10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tva10%'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='ticket_tax20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tva20%'),
        ),
    ]
