# Generated by Django 3.1 on 2021-04-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0008_auto_20210404_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='配送时间'),
        ),
    ]
