# Generated by Django 3.1 on 2021-04-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0009_dataticket_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrint',
            fields=[
                ('print_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='打印编号')),
                ('print_type', models.IntegerField(max_length=10, verbose_name='打印类型')),
                ('print_content', models.CharField(max_length=8192, verbose_name='打印内容')),
            ],
            options={
                'verbose_name': '打印队列',
                'db_table': 'data_print',
                'managed': True,
            },
        ),
    ]
