# Generated by Django 3.1 on 2021-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0011_auto_20210429_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataticket',
            name='ticket_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='整单减免'),
        ),
    ]
