# Generated by Django 3.1 on 2021-05-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0012_auto_20210509_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='payment_history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='付款历史'),
        ),
    ]
