# Generated by Django 3.1 on 2021-05-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0013_dataticket_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='ticket_restaurant_count',
            field=models.IntegerField(default=0, verbose_name='饭票张数'),
        ),
    ]
