# Generated by Django 3.1 on 2023-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0015_auto_20210521_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadish',
            name='dfrname',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='emergency',
            field=models.IntegerField(choices=[(0, '普通'), (1, '优先'), (2, '延后')], default=0, verbose_name='加急状态'),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='ticket_emergency',
            field=models.IntegerField(choices=[(0, '普通'), (1, '优先'), (2, '延后')], default=0, verbose_name='加急状态'),
        ),
    ]
