# Generated by Django 3.1 on 2023-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0016_auto_20230223_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataticket',
            name='payment_history',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='付款历史'),
        ),
    ]
