# Generated by Django 3.1 on 2023-05-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0017_auto_20230417_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataorder',
            name='is_served',
            field=models.IntegerField(choices=[(0, '未上菜'), (1, '已上菜')], default=0, verbose_name='出菜状态'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='ticket_is_served',
            field=models.IntegerField(choices=[(0, '未完全出齐'), (1, '已全部出齐')], default=0, verbose_name='订单出菜状态'),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='prepare_status',
            field=models.IntegerField(choices=[(0, '预定'), (1, '准备中'), (2, '已备齐'), (3, '已完成'), (4, '已上菜')], default=1, verbose_name='准备状态'),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='ticket_status',
            field=models.IntegerField(choices=[(0, '预约订单'), (1, '准备中'), (2, '已完成'), (3, '已取消'), (4, '已上菜')], default=0, verbose_name='订单状态'),
        ),
    ]
