# Generated by Django 3.1 on 2023-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0018_auto_20230517_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorder',
            name='emergency',
            field=models.IntegerField(choices=[(0, '优先'), (1, '普通'), (2, '延后')], default=1, verbose_name='加急状态'),
        ),
    ]
