# Generated by Django 3.1 on 2024-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0019_auto_20230517_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadish',
            name='drecipe',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='ticket_emergency',
            field=models.IntegerField(choices=[(0, '优先'), (1, '普通'), (2, '延后')], default=1, verbose_name='加急状态'),
        ),
    ]
