# Generated by Django 3.1 on 2024-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0020_auto_20240113_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='ticket_pickup_time',
            field=models.IntegerField(default=0, verbose_name='取餐时间'),
        ),
    ]
