# Generated by Django 3.1 on 2024-01-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0021_dataticket_ticket_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataticket',
            name='ticket_pickup_time',
            field=models.CharField(default=0, max_length=20, verbose_name='取餐时间'),
        ),
    ]
