# Generated by Django 3.1 on 2026-03-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0022_auto_20240128_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKitchenCleaningTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_manager', models.CharField(max_length=50, verbose_name='任务负责人')),
                ('task_duration', models.IntegerField(default=0, verbose_name='任务时长(分钟)')),
                ('task_frequency', models.IntegerField(default=1, help_text='1代表每天，7代表每周', verbose_name='任务频率(天)')),
                ('last_completed_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='最近完成时间')),
                ('completion_history', models.TextField(blank=True, help_text='记录最近30次完成时间', null=True, verbose_name='完成历史')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('task_status', models.IntegerField(choices=[(0, '待完成'), (1, '已完成')], default=0, verbose_name='任务状态')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='区域')),
            ],
            options={
                'verbose_name': '厨房清洁任务',
                'db_table': 'data_kitchen_cleaning_task',
                'managed': True,
            },
        ),
    ]
