# Generated by Django 3.1 on 2026-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_beta_02', '0023_datakitchencleaningtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadish',
            name='dmininame',
            field=models.CharField(default=' ', max_length=255, verbose_name='菜品简称'),
        ),
    ]
